# Generated by Django 4.1.7 on 2023-03-14 07:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0008_book_readers_alter_book_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRelations',
            new_name='UserBookRelation',
        ),
    ]
